export const productDB = [
  {
    id: '0',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '1',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '2',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '3',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '4',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '5',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '6',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '7',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '8',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '9',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '10',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '11',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '12',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '13',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '14',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '15',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '16',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '17',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '18',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '19',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '20',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '21',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '22',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '23',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '24',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '25',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '26',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '27',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '28',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '29',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '30',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '31',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '32',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '33',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '34',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '35',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '36',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '37',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '38',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '39',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '40',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '41',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '42',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '43',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '44',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '45',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '46',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '47',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '48',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '49',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '50',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '51',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '52',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '53',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '54',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '55',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '56',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '57',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '58',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '59',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '60',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '61',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '62',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '63',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '64',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '65',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '66',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '67',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '68',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '69',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '70',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '71',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '72',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '73',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '74',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '75',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '76',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '77',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '78',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '79',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '80',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '81',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '82',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '83',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '84',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '85',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '86',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '87',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '88',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '89',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '90',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '91',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '92',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '93',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '94',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
  {
    id: '95',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '96',
    name: 'Syltherine',
    description: 'Stylish cafe chair',
    price: 2500000,
    priceOld: 3500000,
    discountPrice: 30,
    imageUrl: '/src/assets/images/product_01.png',
  },
  {
    id: '97',
    name: 'Lolito',
    description: 'Luxury big sofa',
    price: 7000000,
    priceOld: 14000000,
    discountPrice: 50,
    imageUrl: '/src/assets/images/product_03.png',
  },
  {
    id: '98',
    name: 'Leviosa',
    description: 'Stylish cafe chair',
    price: 2500000,
    imageUrl: '/src/assets/images/product_02.png',
  },
  {
    id: '99',
    name: 'Respira',
    description: 'Outdoor bar table and stool',
    price: 500000,
    new: true,
    imageUrl: '/src/assets/images/product_04.png',
  },
]
